### ISSUE TITLE
Error after Add Product

### ISSUE THREAD

**Issue by srgrbkl** [zepgram/magento2-fast-vm#92]
When trying to add product i get error (in backend):
`TypeError: rawurlencode() expects parameter 1 to be string, int given in /home/vagrant/magento/vendor/laminas/laminas-escaper/src/Escaper.php:246 Stack trace: #0 /home/vagrant/magento/vendor/laminas/laminas-escaper/src/Escaper.php(246): rawurlencode() #1 /home/vagrant/magento/vendor/magento/framework/Escaper.php(286): Laminas\Escaper\Escaper->escapeUrl() #2 /home/vagrant/magento/vendor/magento/framework/Url/RouteParamsResolver.php(115): Magento\Framework\Escaper->encodeUrlParam() #3 /home/vagrant/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\Url\RouteParamsResolver->setRouteParams() #4 /home/vagrant/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\Url\RouteParamsResolver\Interceptor->___callParent() #5 /home/vagrant/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\Url\RouteParamsResolver\Interceptor->Magento\Framework\Interception\{closure}() #6 /home/vagrant/magento/generated/code/Magento/Framework/Url/RouteParamsResolver/Interceptor.php(23): Magento\Framework\Url\RouteParamsResolver\Interceptor->___callPlugins() #7 /home/vagrant/magento/vendor/magento/framework/Url.php(716): Magento\Framework\Url\RouteParamsResolver\Interceptor->setRouteParams() #8 /home/vagrant/magento/vendor/magento/module-backend/Model/Url.php(189): Magento\Framework\Url->_setRouteParams() #9 /home/vagrant/magento/vendor/magento/framework/Url.php(754): Magento\Backend\Model\Url->_setRouteParams() #10 /home/vagrant/magento/vendor/magento/framework/Url.php(929): Magento\Framework\Url->getRouteUrl() #11 /home/vagrant/magento/vendor/magento/framework/Url.php(873): Magento\Framework\Url->createUrl() #12 /home/vagrant/magento/vendor/magento/module-backend/Model/Url.php(210): Magento\Framework\Url->getUrl() #13 /home/vagrant/magento/vendor/magento/module-catalog/Ui/DataProvider/Product/Form/Modifier/Categories.php(216): Magento\Backend\Model\Url->getUrl() #14 /home/vagrant/magento/vendor/magento/module-catalog/Ui/DataProvider/Product/Form/Modifier/Categories.php(148): Magento\Catalog\Ui\DataProvider\Product\Form\Modifier\Categories->createNewCategoryModal() #15 /home/vagrant/magento/vendor/magento/module-catalog/Ui/DataProvider/Product/Form/ProductDataProvider.php(73): Magento\Catalog\Ui\DataProvider\Product\Form\Modifier\Categories->modifyMeta() #16 /home/vagrant/magento/vendor/magento/framework/View/Element/UiComponentFactory.php(330): Magento\Catalog\Ui\DataProvider\Product\Form\ProductDataProvider->getMeta() #17 /home/vagrant/magento/vendor/magento/framework/View/Element/UiComponentFactory.php(231): Magento\Framework\View\Element\UiComponentFactory->mergeMetadata() #18 /home/vagrant/magento/vendor/magento/framework/View/Layout/Generator/UiComponent.php(140): Magento\Framework\View\Element\UiComponentFactory->create() #19 /home/vagrant/magento/vendor/magento/framework/View/Layout/Generator/UiComponent.php(103): Magento\Framework\View\Layout\Generator\UiComponent->generateComponent() #20 /home/vagrant/magento/vendor/magento/framework/View/Layout/GeneratorPool.php(93): Magento\Framework\View\Layout\Generator\UiComponent->process() #21 /home/vagrant/magento/vendor/magento/framework/View/Layout.php(365): Magento\Framework\View\Layout\GeneratorPool->process() #22 /home/vagrant/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(68): Magento\Framework\View\Layout->generateElements() #23 /home/vagrant/magento/vendor/magento/framework/View/Layout/Builder.php(129): Magento\Framework\View\Layout\Interceptor->generateElements() #24 /home/vagrant/magento/vendor/magento/framework/View/Page/Builder.php(65): Magento\Framework\View\Layout\Builder->generateLayoutBlocks() #25 /home/vagrant/magento/vendor/magento/framework/View/Layout/Builder.php(65): Magento\Framework\View\Page\Builder->generateLayoutBlocks() #26 /home/vagrant/magento/vendor/magento/framework/View/Layout.php(271): Magento\Framework\View\Layout\Builder->build() #27 /home/vagrant/magento/vendor/magento/framework/View/Layout.php(896): Magento\Framework\View\Layout->build() #28 /home/vagrant/magento/generated/code/Magento/Framework/View/Layout/Interceptor.php(293): Magento\Framework\View\Layout->getBlock() #29 /home/vagrant/magento/vendor/magento/module-backend/Model/View/Result/Page.php(26): Magento\Framework\View\Layout\Interceptor->getBlock() #30 /home/vagrant/magento/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(23): Magento\Backend\Model\View\Result\Page->setActiveMenu() #31 /home/vagrant/magento/vendor/magento/module-catalog/Controller/Adminhtml/Product/NewAction.php(72): Magento\Backend\Model\View\Result\Page\Interceptor->setActiveMenu() #32 /home/vagrant/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Controller\Adminhtml\Product\NewAction->execute() #33 /home/vagrant/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->___callParent() #34 /home/vagrant/magento/vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php(51): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->Magento\Framework\Interception\{closure}() #35 /home/vagrant/magento/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute() #36 /home/vagrant/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->Magento\Framework\Interception\{closure}() #37 /home/vagrant/magento/generated/code/Magento/Catalog/Controller/Adminhtml/Product/NewAction/Interceptor.php(23): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->___callPlugins() #38 /home/vagrant/magento/vendor/magento/framework/App/Action/Action.php(111): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->execute() #39 /home/vagrant/magento/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch() #40 /home/vagrant/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch() #41 /home/vagrant/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->___callParent() #42 /home/vagrant/magento/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->Magento\Framework\Interception\{closure}() #43 /home/vagrant/magento/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() #44 /home/vagrant/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->Magento\Framework\Interception\{closure}() #45 /home/vagrant/magento/generated/code/Magento/Catalog/Controller/Adminhtml/Product/NewAction/Interceptor.php(32): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->___callPlugins() #46 /home/vagrant/magento/vendor/magento/framework/App/FrontController.php(186): Magento\Catalog\Controller\Adminhtml\Product\NewAction\Interceptor->dispatch() #47 /home/vagrant/magento/vendor/magento/framework/App/FrontController.php(118): Magento\Framework\App\FrontController->processRequest() #48 /home/vagrant/magento/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch() #49 /home/vagrant/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent() #50 /home/vagrant/magento/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() #51 /home/vagrant/magento/generated/code/Magento/Framework/App/FrontController/Interceptor.php(23): Magento\Framework\App\FrontController\Interceptor->___callPlugins() #52 /home/vagrant/magento/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch() #53 /home/vagrant/magento/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http->launch() #54 /home/vagrant/magento/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch() #55 /home/vagrant/magento/pub/index.php(29): Magento\Framework\App\Bootstrap->run() #56 {main}`

**Comment by srgrbkl** [comment]
error  fixed after reload machine
